# Generated by Django 4.2.11 on 2024-04-28 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('abstract', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaperMetaDataAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaperMetaDataInstitutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaperSourceTOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaperTOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField()),
                ('critical_concepts', models.TextField()),
                ('domain_task_problem', models.TextField()),
                ('motivations_priorities', models.TextField()),
                ('eval_metrics', models.TextField()),
                ('approach', models.TextField()),
                ('results', models.TextField()),
                ('future_work', models.TextField()),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesisapp.papermetadata')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='PDFPaper',
        ),
        migrations.AddField(
            model_name='papersourcetou',
            name='tou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesisapp.papertou'),
        ),
        migrations.AddField(
            model_name='papermetadatainstitutions',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesisapp.researchinstitution'),
        ),
        migrations.AddField(
            model_name='papermetadatainstitutions',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesisapp.papermetadata'),
        ),
        migrations.AddField(
            model_name='papermetadataauthors',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesisapp.person'),
        ),
        migrations.AddField(
            model_name='papermetadataauthors',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesisapp.papermetadata'),
        ),
    ]
