# Generated by Django 4.2.11 on 2024-05-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0003_alter_papermetadata_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papermetadata',
            name='abstract_emb',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='papermetadata',
            name='title_emb',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='papertou',
            name='approach_emb',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='papertou',
            name='critical_concepts_emb',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='papertou',
            name='domain_task_problem_emb',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='papertou',
            name='eval_metrics_emb',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='papertou',
            name='future_work_emb',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='papertou',
            name='motivations_priorities_emb',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='papertou',
            name='overview_emb',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='papertou',
            name='results_emb',
            field=models.BinaryField(blank=True),
        ),
    ]
