# Generated by Django 4.2.11 on 2024-05-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0004_papermetadata_abstract_emb_papermetadata_title_emb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papermetadata',
            name='keywords_emb',
            field=models.BinaryField(blank=True),
        ),
    ]
