# Generated by Django 4.2.11 on 2024-05-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0006_alter_papermetadata_abstract_emb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertou',
            name='domain_task_problem_emb',
            field=models.BinaryField(blank=True, max_length=2000000),
        ),
    ]
